apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p2p-system

resources:
  - namespace.yaml
  - tracker-deployment.yaml
  - peer-statefulset.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: p2p-filesharing
  app.kubernetes.io/managed-by: kustomize

images:
  - name: registry.idist.dev/p2p/tracker
    newTag: latest
  - name: registry.idist.dev/p2p/peer
    newTag: latest

