apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: p2p-system
type: kubernetes.io/dockerconfigjson
data:
  # This will be created by kubectl command, placeholder here
  .dockerconfigjson: eyJhdXRocyI6e319
---
# Create this secret using:
# kubectl create secret docker-registry registry-credentials \
#   --docker-server=registry.idist.dev \
#   --docker-username=idist-hn \
#   --docker-password=HanhHanh2508@ \
#   -n p2p-system

